server:
  port: ${CLIENT_SERVICE_PORT:8081}
  forward-headers-strategy: framework

spring:
  application:
    name: client-service

# ----------------------------
# OpenAPI / Swagger
# ----------------------------
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# ----------------------------
# Configuration OpenAPI (optionnelle)
# ----------------------------
openapi:
  service:
    title: client-service doc
    version: 1.0.0
    url: http://localhost:${CLIENT_SERVICE_PORT:8081}

# ----------------------------
# Base de données PostgreSQL
# ----------------------------
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://dbclient:5432/dbclient}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# ----------------------------
# Actuator
# ----------------------------
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    db:
      enabled: true
