server:
  port: ${CLIENT_SERVICE_PORT}
  forward-headers-strategy: framework   # ← IMPORTANT pour Swagger derrière Gateway

spring:
  application:
    name: client-service

# ----------------------------
# SPRINGDOC — SWAGGER
# ----------------------------
springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: client-service
        url: /client-service/v3/api-docs

# ----------------------------
# DATABASE PostgreSQL
# ----------------------------
  datasource:
    url: ${SPRING_DATASOURCE_URL_SOCIETE:jdbc:postgresql://dbsclient:5433/dbclient}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# ----------------------------
# ACTUATOR
# ----------------------------
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    db:
      enabled: true
