server:
  port: ${CLIENT_SERVICE_PORT}
  forward-headers-strategy: framework
  
openapi:
  service:
    title: client-service doc # title that you will want to display in the Swagger UI
    version: 1.0.0
    url: http://localhost:8080
springdoc:
  api-docs:
    path: /client-service/v3/api-docs  
  swagger-ui:
    path: /client-service/swagger-ui.html        

spring:
  application:
    name: client-service

# ----------------------------
# Configuration de la base PostgreSQL
# ----------------------------
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://dbclient:5432/dbclient}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# ----------------------------
# Actuator pour health check
# ----------------------------
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    db:
      enabled: true
