server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false   # Le serveur ne s'enregistre pas lui-même
    fetch-registry: false         # Il ne récupère pas d'autres registres
  server:
    enable-self-preservation: false  # Pour le développement uniquement
logging:
  level:
    root: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh  # Utile si tu veux recharger la config à chaud
