server:
  port: ${GATEWAY_SERVICE_PORT:8083}
  forward-headers-strategy: framework

spring:
  application:
    name: gateway-service

  output:
    ansi:
      enabled: always

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:

        # ==========================
        # SOCIETE SERVICE
        # ==========================
        - id: societe-service
          uri: lb://societe-service
          predicates:
            - Path=/societe-service/**
          filters:
            - StripPrefix=1

        # ==========================
        # CLIENT SERVICE
        # ==========================
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/client-service/**
          filters:
            - StripPrefix=1

        # ==========================
        # OPENAPI (Swagger JSON)
        # ==========================
        - id: openapi-societe
          uri: lb://societe-service
          predicates:
            - Path=/societe-service/v3/api-docs

        - id: openapi-client
          uri: lb://client-service
          predicates:
            - Path=/client-service/v3/api-docs

# ==========================
# SPRINGDOC - SWAGGER UI CENTRALISÉ
# ==========================
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: client-service
        url: /client-service/v3/api-docs
      - name: societe-service
        url: /societe-service/v3/api-docs

  forward-headers-strategy: framework

# ==========================
# LOGGING (DEBUG GATEWAY)
# ==========================
logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO
