server:
  port: ${GATEWAY_SERVICE_PORT}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: client-service
        url: /v3/api-docs/client-service
      - name: societe-service
        url: /v3/api-docs/societe-service
spring:
  cloud:
    gateway:
      routes:

        # ================================
        # CLIENT-SERVICE
        # ================================
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/client-service/** , /client-servic/v3/api-docs
          filters:
            - StripPrefix=1

        # ================================
        # SOCIETE-SERVICE
        # ================================
        - id: societe-service
          uri: lb://societe-service
          predicates:
            - Path=/societe-service/**
          filters:
            - RewritePath=/societe-service/(?<segment>.*), /${segment}
            - AddRequestHeader=X-Forwarded-Prefix, /societe-service
            - AddRequestHeader=X-Forwarded-Host, localhost:${GATEWAY_SERVICE_PORT}
