server:
  port: ${GATEWAY_SERVICE_PORT}

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /client-service/v3/api-docs
        name: Client Service
        
    
spring:
  cloud:
    gateway:
      routes:

        # ================================
        # CLIENT-SERVICE
        # ================================
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/client-service/**
          filters:
            - RewritePath=/client-service/(?<segment>.*), /client-service/${segment}
}
