server:
  port: ${GATEWAY_SERVICE_PORT}
  forward-headers-strategy: framework

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:

        # ================================
        # CLIENT-SERVICE
        # ================================
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/client-service/**
          filters:
            - RewritePath=/client-service/(?<segment>.*), /${segment}
            - AddRequestHeader=X-Forwarded-Prefix, /client-service

        # ================================
        # SOCIETE-SERVICE
        # ================================
        - id: societe-service
          uri: lb://societe-service
          predicates:
            - Path=/societe-service/**
          filters:
            - RewritePath=/societe-service/(?<segment>.*), /${segment}
            - AddRequestHeader=X-Forwarded-Prefix, /societe-service

# ==========================
# SPRINGDOC - SWAGGER UI CENTRALISÉ
# ==========================
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: client-service
        url: /client-service/v3/api-docs
      - name: societe-service
        url: /societe-service/v3/api-docs

# ==========================
# LOGGING
# ==========================
logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO
