server:
  port: ${SOCIETE_SERVICE_PORT}

spring:
  application:
    name: societe-service
  datasource:
    url: ${SPRING_DATASOURCE_URL_SOCIETE}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false   # Swagger UI seulement dans le gateway
  servers:
    - url: http://localhost:8083/societe-service
      description: API Societe via Gateway

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    db:
      enabled: true
