server:
  port: ${SOCIETE_SERVICE_PORT}
  forward-headers-strategy: framework   # ← IMPORTANT pour Swagger derrière Gateway

spring:
  application:
    name: societe-service

# ----------------------------
# SPRINGDOC — SWAGGER
# ----------------------------
springdoc:
  api-docs:
    path: /v3/api-docs     # ← NE PAS mettre /societe-service
  swagger-ui:
    path: /swagger-ui/index.html
    disable-swagger-default-url: true   # ← Facultatif : évite les conflits

# ----------------------------
# DATABASE PostgreSQL
# ----------------------------
  datasource:
    url: ${SPRING_DATASOURCE_URL_SOCIETE:jdbc:postgresql://dbsociete:5432/dbsociete}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# ----------------------------
# ACTUATOR
# ----------------------------
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    db:
      enabled: true
